---

- hosts: rockesxi001
  gather_facts: true
  become: true
    #  vars_files:
    #- ./roles/redhat/docker/vars/docker-users.yaml
  roles: 
    -  { role: roles/redhat/docker }
      #      when: ansible_facts['distribution_file_variety'] == 'RedHat'


