---

- hosts: rockesxi001
  gather_facts: true
  become: true
  vars_files:
    - ./roles/redhat/docker/vars/docker-users.yaml
  tasks: 
    - name: 'Install Docker Engine and containerd on selected hosts'
      include_tasks: ./roles/redhat/docker/tasks/main.tf
      when: ansible_facts['distribution_file_variety'] == 'RedHat'

