---

- hosts: all
  gather_facts: true
  tasks: 
    - name: 'Fetch System OS details'
      debug: 
        msg: OS Version = {{ ansible_distribution }} {{ ansible_distribution_major_version }} {{ ansible_distribution_release }} {{ ansible_distribution_file_variety }} 
